services:
  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --reload-dir .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

    depends_on:
      - redis
      - fastapi
    env_file:
      - .env
    volumes:
      - .:/code

volumes:
  mysql_data:
